comment: off
# show coverage in CI status, but never consider it a failure
coverage:
  status:
    project:
      default:
        target: 50%
    patch:
      default:
        target: 50%
ignore:
  - "tvbwidgets/tests"
